### ISSUE TITLE
crash on add event to schedule

### ISSUE THREAD

**Issue by dartuso** [awave1/fitness-tracker#32]
Process: com.group15.fitnesstracker, PID: 7760
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)
        at com.group15.fitnesstracker.dashboard.schedule.CreateScheduleItemDialogFactory$Companion$create$7.onClick(CreateScheduleItemDialogFactory.kt:144)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:177)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by dartuso** [comment]
im dumb its cuz no workout selected but still a error i guess
